### PR TITLE
Hotfix - clean input after staking and updated title text

### PR DESCRIPTION
**Pull request by jeremy-babylonlabs**
- [x] Improved staking clear input logic
- [x] updated staking and FP title text

### CODE REVIEW

**Review by gbarkhatov — COMMENTED** [review]
@jeremy-babylonlabs  Do we need to count the resets as state?

**Comment by vitsalis** [comment]
I don't understand why are we counting resets

**Comment by jeremy-babylonlabs** [comment]
using a reset counter can make sure the states rerenders in the lifecycle. but agreed and going with @jrwbabylonlab's approach for now.

**Review by gbarkhatov — APPROVED** [review]
@jeremy-babylonlabs I suggest we do add `strong` to steps, so it's more emphasized for the end user (for both steps)
```
      <p>
        <strong>Step-1:</strong> Select a finaltiy provider
      </p> 
```

Other than that PR does what it should - resets the amount

**Pull request merged**
